version: '3.9'
services:
  api:
    build:
      context: .
      target: runner
      args:
        - MONGO_URI_ATLAS=mongodb://dbmongo:27017/rps-db
    container_name: node-api-rps
    ports:
      # host:container
      - "3002:3002"
    restart: always
    links:
      - dbmongo
  dbmongo:
    image: mongo
    container_name: dbmongo-rps
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=rps-db
    volumes:
      - dbmongo-api-rps:/data/db
volumes:
  dbmongo-api-rps:
